* *********************************************************
* *
* * 10/10/2019             MYDATA1.DBC             00:46:21
* *
* *********************************************************
* *
* * Description:
* * This program was automatically generated by GENDBC
* * Version 2.26.67
* *
* *********************************************************


DisplayStatus([Creating database...])
CLOSE DATA ALL
CREATE DATABASE 'MYDATA1.DBC'
DisplayStatus([Creating table VANZATOR...])
MakeTable_VANZATOR()
DisplayStatus([Finished.])

FUNCTION MakeTable_VANZATOR
***** Table setup for VANZATOR *****
CREATE TABLE 'VANZATOR.DBF' NAME 'VANZATOR' (ID C(6) NOT NULL, ;
                       NUME C(20) NOT NULL)

***** Create each index for VANZATOR *****
INDEX ON ID TAG ID COLLATE 'MACHINE'

***** Change properties for VANZATOR *****
ENDFUNC


FUNCTION DisplayStatus(lcMessage)
WAIT WINDOW NOWAIT lcMessage
ENDFUNC
